[package]
name = "rust_rocket_ws"
version = "0.1.0"
authors = ["dgreat91 <dgreat91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
